backend:
  name: git-gateway
  branch: master

media_folder: 'assets/images'
publish_mode: editorial_workflow

collections:
  - name: 'wiki'
    label: 'Wiki Post'
    folder: 'docs'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
